name: handle-dispatch
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
 
jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Print event info
        run: |
          echo "HELLO"